### PR TITLE
Enhancement read me

### PR DESCRIPTION
**Pull request by kelset**
First PR - let's try this... so:
1) modified the README file to be more uniform with the others projects
2) added the yarn.lock file (or should it be in .gitignore?)

btw this PR is a branch of the RN0.33 branch you made. I tested it on the iOS simulator and it builds and runs.

### CODE REVIEW

**Review by Proyoyo — CHANGES_REQUESTED** [review]
README changes looks good. However, changes in other files (build.gradle, settings.gradle, .xcodeproj, etc) are unnecessary.

**Comment by howardchung** [comment]
@kelset any update on this?

**Comment by kelset** [comment]
hey @howardchung sorry I disappeared: a lot of stuff currently going on IRL, I'll move to London in a couple weeks (new job, new country, new life).
Once that is over I'll may be able to spare some time to get back here but for now I can't make any promises :/

**Comment by Proyoyo** [comment]
Closing this because the changes are incorporated in PR #3

**Pull request closed without merging**
