### PR TITLE
scroll to top when pressing next and previous buttons

### LINKED ISSUE #127: When going to next page, screen should scroll back to top
Expected: 
On Matches, Heroes, and Peers pages, when a user clicks `<` or `>`, they should be navigated back to the top of the page.

Actual:
The user is left viewing the bottom of the screen

### PR DESCRIPTION
**Pull request by ganes1410**
Fixes #127

### CODE REVIEW

**Comment by ganes1410** [comment]
@Proyoyo  can you please review this

**Comment by ganes1410** [comment]
@Proyoyo  I made a commit with different account.Do you know how to revert this?

**Comment by Proyoyo** [comment]
@ganes1410 

Hi, I can have a look at this in a few days. Things are currently quite busy with my day job so I don't have the time to review & test this at the moment.

**Comment by ganes1410** [comment]
@Proyoyo cool. Just take a look at this when you have time

**Review by Proyoyo — APPROVED** [review]

**Pull request merged**
