### PR TITLE
fix heatmap on ios

### PR DESCRIPTION
**Pull request by anhmiuhv**

### CODE REVIEW

**Comment by Proyoyo** [comment]
@anhmiuhv @vocosu I'll test this tomorrow and if there's no issue, I'll merge it.

**Review by Proyoyo — CHANGES_REQUESTED** [review]
img_1072

I've tested it and it seems that in iOS, after opening several heatmaps, there's scaling issue as depicted in the screenshot above. This is a consistent behaviour when I tested it with iPhone 6S+ iOS 11 and iPhone 5S iOS 10. I'm not sure what's causing this issue. @anhmiuhv

**Comment by anhmiuhv** [comment]
@Proyoyo the WebView on iOS is quite weird. I have to execute the heat map drawing 100 ms after loading the map image for it to work.

**Review by Proyoyo — APPROVED** [review]
There's some weird edge case bug on iOS where the scaling issue appears after the user show/hide the same player's heatmap multiple times, then opening other player's heatmap. 

However, with normal use case, this shouldn't happen too often. As such, I'll approve this PR and we can fix the edge case bug later on.

**Comment by Proyoyo** [comment]
@anhmiuhv @vocosu

**Pull request merged**
