### PR TITLE
Refactorings and Cleanups

### PR DESCRIPTION
**Pull request by nzmedet**
This is eslint configs for cleaner code

RFC @Proyoyo @all

### CODE REVIEW

**Review by Proyoyo — COMMENTED** [review]
There was an issue with Mobile Center automated build & beta distribution when I included package-lock.json & yarn.lock in the past. We can try adding them in again. However, if it causes build issue, they need to be removed in the beta branch.

**Comment by nzmedet** [comment]
removed package-lock, yarn-lock files

**Review by Proyoyo — CHANGES_REQUESTED** [review]
packages need to be updated before removing the "^". Old version of packages are causing build issue (e.g. reat-native-spinkit 1.0.2).

I fixed it by updating package.json to:
    "dotaconstants": "5.11.0",
    "heatmap.js": "2.0.5",
    "lodash": "4.17.4",
    "mobile-center": "0.7.0",
    "mobile-center-analytics": "0.7.0",
    "mobile-center-crashes": "0.7.0",
    "moment": "2.18.1",
    "react": "16.0.0-alpha.12",
    "react-native": "0.48.4",
    "react-native-keyboard-aware-scroll-view": "0.3.0",
    "react-native-material-design": "0.3.7",
    "react-native-material-design-styles": "0.2.7",
    "react-native-navbar": "1.8.0",
    "react-native-root-toast": "git+https://github.com/Proyoyo/react-native-root-toast.git",
    "react-native-router-flux": "4.0.0-beta.21",
    "react-native-scrollable-tab-view": "0.7.4",
    "react-native-slider": "0.9.1",
    "react-native-spinkit": "1.1.1",
    "react-native-vector-icons": "4.4.0",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-thunk": "2.2.0"

When I tried to build your fork, I'm having path issue with the babelrc. Need to add "cwd": "babelrc" before "alias" to fix the issue.

It seems that after initial install, default colors are not applied correctly in your fork. I'm still not quite sure what's causing this issue but it needs to be fixed before it's merged.

In HeroesCard.js, localizedName always resolves to null.

**Comment by Proyoyo** [comment]
Gonna close this since it's inactive @vko-online

**Pull request closed without merging**
